/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 inspired tokens (reference theme)
        secondary: '#496172',
        outline: '#75777a',
        'on-tertiary-fixed-variant': '#454748',
        surface: '#f6faff',
        'surface-container-highest': '#dbe4ed',
        'on-tertiary-fixed': '#191c1d',
        'on-error': '#ffffff',
        'tertiary-container': '#191c1d',
        'surface-dim': '#d2dbe4',
        'surface-bright': '#f6faff',
        'surface-container-lowest': '#ffffff',
        background: '#f6faff',
        'on-tertiary-container': '#828485',
        'secondary-container': '#cce6fa',
        'surface-container-low': '#ecf5fe',
        'on-tertiary': '#ffffff',
        primary: '#000101',
        tertiary: '#000000',
        'inverse-primary': '#c6c6c9',
        'secondary-fixed': '#cce6fa',
        'primary-fixed-dim': '#c6c6c9',
        'on-secondary': '#ffffff',
        'on-primary-container': '#838486',
        'inverse-on-surface': '#e9f2fb',
        'on-surface-variant': '#44474a',
        'tertiary-fixed-dim': '#c5c7c8',
        'primary-fixed': '#e2e2e5',
        'on-secondary-fixed': '#031e2d',
        'on-primary-fixed': '#1a1c1e',
        'surface-container': '#e6eff8',
        'on-error-container': '#93000a',
        'outline-variant': '#c5c6ca',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#454749',
        'on-secondary-fixed-variant': '#324a5a',
        'inverse-surface': '#293138',
        error: '#ba1a1a',
        'surface-variant': '#dbe4ed',
        'on-secondary-container': '#4f6778',
        'surface-container-high': '#e0e9f2',
        'on-surface': '#141d23',
        'primary-container': '#1a1c1e',
        'tertiary-fixed': '#e1e3e4',
        'on-background': '#141d23',
        'error-container': '#ffdad6',
        'surface-tint': '#5d5e61',
        'secondary-fixed-dim': '#b1cadd',

        // Legacy tokens (kept for admin layer)
        brand: {
          50:  '#eef4ff',
          100: '#dbe7ff',
          200: '#bfd4ff',
          300: '#93b6ff',
          400: '#608dff',
          500: '#3a66ff',
          600: '#2447f5',
          700: '#1c36d8',
          800: '#1c30ad',
          900: '#1d2f88',
          950: '#141c4f',
        },
        accent: {
          400: '#22d3ee',
          500: '#06b6d4',
          600: '#0891b2',
        },
        ink: {
          50:  '#f7f8fb',
          100: '#eceff5',
          200: '#d6dbe7',
          300: '#b1bacd',
          400: '#7e8aa6',
          500: '#5b6685',
          600: '#404a66',
          700: '#2f3650',
          800: '#1f2438',
          900: '#141828',
          950: '#0a0d18',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-padding': '120px',
        'stack-sm': '16px',
        unit: '8px',
        'container-max': '1140px',
        'stack-md': '32px',
        'margin-mobile': '20px',
        gutter: '24px',
        'stack-lg': '64px',
      },
      maxWidth: {
        'container-max': '1140px',
      },
      fontFamily: {
        // Display / headings / labels share Metropolis (reference theme)
        display: ['Metropolis', 'Inter', 'system-ui', 'sans-serif'],
        'display-mobile': ['Metropolis', 'Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Metropolis', 'Inter', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Metropolis', 'Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Metropolis', 'Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Metropolis', 'Inter', 'system-ui', 'sans-serif'],
        // Body uses Source Serif 4
        'body-lg': ['"Source Serif 4"', 'Georgia', 'serif'],
        'body-md': ['"Source Serif 4"', 'Georgia', 'serif'],
        // Legacy aliases (kept for admin layer)
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(31, 38, 135, 0.18)',
        glow: '0 0 40px -10px rgba(58, 102, 255, 0.55)',
        natural: '0px 4px 20px rgba(0, 0, 0, 0.03)',
      },
      backgroundImage: {
        'grid-light': "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='40' viewBox='0 0 40 40'%3E%3Cpath fill='none' stroke='%23e5e7eb' d='M0 0h40v40H0z'/%3E%3C/svg%3E\")",
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s ease-out both',
        float: 'float 4s ease-in-out infinite',
        shimmer: 'shimmer 1.6s linear infinite',
        blink: 'blink 1s steps(1) infinite',
      },
    },
  },
  plugins: [],
}
